# ---------- Stage 1: Build ----------
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/main.go

# ---------- Stage 2: Runtime ----------
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/main .

EXPOSE 9000

CMD ["./main"]
