stage('Build Backend Image') {
    steps {
        dir('server') {
            sh 'docker build -t $GO_IMAGE:latest .'
        }
    }
}

stage('Build Frontend Image') {
    steps {
        dir('ui') {
            sh 'docker build -t $FE_IMAGE:latest .'
        }
    }
}

stage('Push Images') {
    steps {
        withDockerRegistry([credentialsId: 'dockerhub-creds']) {
            sh 'docker push $GO_IMAGE:latest'
            sh 'docker push $FE_IMAGE:latest'
        }
    }
}

stage('Deploy to EKS') {
    steps {
        sh 'kubectl apply -f k8s/'
    }
}
