pipeline {
    agent any

    environment {
        AWS_REGION   = 'ap-southeast-2'
        CLUSTER_NAME = 'my-eks-cluster'
        IMAGE_NAME   = 'jayekmr/go-todo'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jayekmr/k8s-todo.git',
                    credentialsId: 'github-cred'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "./server")
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-cred-id') {
                        sh "docker push ${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Configure kubeconfig (EKS Login)') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-eks-credentials-id'
                ]]) {
                    sh '''
                        aws eks update-kubeconfig \
                        --region $AWS_REGION \
                        --name $CLUSTER_NAME

                        kubectl get nodes
                    '''
                }
            }
        }

        stage('Deploy Kubernetes Manifests') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }

        stage('Update Deployment Image') {
            steps {
                sh '''
                  kubectl set image deployment/go-app-deployment \
                  go-app=${IMAGE_NAME}:latest
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -o wide'
                sh 'kubectl get svc'
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful!"
        }
        failure {
            echo "❌ Deployment failed!"
        }
    }
}
